### ISSUE TITLE
Reports not generated after moving from Thucydides to Serenity

### ISSUE THREAD

**Issue by mthmulders** [serenity-bdd/serenity-maven-plugin#1]
Just switched from Thucydides to Serenity BDD; now my report isn't being generated. I have the following dependencies in my pom.xml:
- net.serenity-bdd:core:1.0.6
- net.serenity-bdd:serenity-junit:1.0.6
- net.serenity-bdd:serenity-cucumber:1.0.2 (no 1.0.6 here?)

and the following plugins
- net.serenity-bdd.maven.plugins:1.0.6
- org.apache.maven.plugins:maven-site-plugin:3.4 with reportPlugins -> net.serenity-bdd.maven.plugins:1.0.6.

Using Maven 3.0.5 on Java 8, I have get this message:

> [ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.6:aggregate (thucydides-reports) on project styd-test: Execution thucydides-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.6:aggregate failed: An API incompatibility was encountered while executing net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.6:aggregate: java.lang.IllegalAccessError: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class com.google.inject.internal.Annotations$AnnotationChecker

What could be the issue here?

**Comment by prak0628** [comment]
In my group , we are using serenity with JBehave . We are trying to create an executable jar for our functional testers so that they can double click on the jar and execute the test.For the same iam not able to call the aggregate phase since the executable jar does not have a pom.xml to do so.
May i please know is there any way for us to create JSON reports and the call the aggregate method via java code for eg: In @afterStories annotation. Please advice on this.
