### ISSUE TITLE
Aggregate report problems in multimodule Maven build

### ISSUE THREAD

**Issue by TuireHolappa** [serenity-bdd/serenity-maven-plugin#11]
After upgrading from Serenity Maven plugin 1.0.47 > 1.1.5 the nice Serenity aggregate reports do not get generated.

Having multimodule Maven project
App
|-bdd
|-etc
Where serenity tests are on the bdd-module.

Running the application level build on Jenkins CI with mvn clean install does not anymore produce the aggregate report like before to App/bdd/target/site/serenity but to App/target/site/serenity. And the problem is that the report is empty.

I tried using some serenity.properties file (bdd/src/main/resources) with items from workaround but that had no effect.
Running the same build cmd on the bdd directory on my own machine does produce the aggregate report correctly.

Any hints how to make aggregate happen on application build?

**Comment by TuireHolappa** [comment]
I found a workaround to define the paths in serenity.properties to point to the application level 
serenity.outputDirectory=../target/site/serenity
serenity.sourceDirectory=../target/site/serenity
This produces old version kind of report.
The report run from the bdd module looks much nicer so I hope this can be corrected.
![reportfromapplevel](https://cloud.githubusercontent.com/assets/13870604/9376686/311a6bb6-4719-11e5-8681-8b7f419171a9.PNG)
![reportfrombddmodule](https://cloud.githubusercontent.com/assets/13870604/9376691/3490085a-4719-11e5-96d3-2c4d603cc63e.PNG)

**Comment by klokovas** [comment]
I use gradle and I have the same problem, but workaround with serenity.sourceDir/outputDir doesn't work.

@TuireHolappa have you any new information about this problem?

**Comment by YamStranger** [comment]
Hello @TuireHolappa thanks for this issue.  It was fixed by #21 pull request, and now reports looks like 
![image](https://cloud.githubusercontent.com/assets/1667699/12278124/fd7725b0-b987-11e5-9967-77d292e19bae.png)
also serenity.ouputDirectory works fine, it was tested against serenity-demos/junit-webtest project.

**Comment by TuireHolappa** [comment]
Hi,

The #21 is not solving this issue. If I do not explicitly define the workround the generated report to the App level is still empty with version 1.1.24. My nose hints that the implementation detail described in  #22 would be the root cause.  

In my opinion the plugin should produce the outcome to the project.build.outputDirectory of the Maven module that it was defined to be run in. In my Maven configuration it is the bdd-module. Now it oddly generates the empty report to the module parent even though the serenity-maven-plugin has not been defined at all at the App-level pom.

**Comment by YamStranger** [comment]
Hello @TuireHolappa. 

I see your last update about issue description:

>I found a workaround to define the paths in serenity.properties to point to the application level 
serenity.outputDirectory=../target/site/serenity
serenity.sourceDirectory=../target/site/serenity
This produces old version kind of report.
The report run from the bdd module looks much nicer so I hope this can be corrected

so, you find some old version of reports and expect new version of reports. Now build generate new version of report, so this problem (and last described by you) is fixed - that is why this issue is closed. 


As I understand you last comment, also you expect that report will be generated only under bdd without any workarounds (according to you structure, where *ONLY* bdd will contains tests)
>Having multimodule Maven project
App
|-bdd
|-etc

*if mvn will run under APP, or under bdd?  (the same as will be fixed with #22 issue)

**Comment by YamStranger** [comment]
Issue closed as duplicate to #22. All fixed will provided under that issue, fix include serenity-core and serenity-maven-plugin (so new versions of them should be used)
